### ISSUE TITLE
请问下这是什么异常？

### ISSUE THREAD

**Issue by hqzh** [Yuki-Minakami/BookExample#3]
![_20181231155804](https://user-images.githubusercontent.com/26128706/50556524-19cf4880-0d15-11e9-9c61-c94fb4021e48.png)

**Comment by hqzh** [comment]
// windows  由此可以说明第一个参数是文件名而非命令，上面的ls在Linux下也是一个ls的可执行文件，而在Windows中并没有名为dir的可执行文件，需要通过cmd或power shell之类的工具提供执行环境
const ls = spawn('cmd', ['dir']);    //这里不知为什么执行的乱码？？？
// const ls = spawn('powershell', ['dir']);

**Comment by Yuki-Minakami** [comment]
你好，
关于第一个问题，代码运行起来后，需要在系统设置里配置127.0.0.1:8080作为代理，
然后使用curl -x localhost:8080 google.com来测试即可

第二个问题不是很明白，能不能再描述详细一些？

**Comment by hqzh** [comment]
![qq 20190101141157](https://user-images.githubusercontent.com/26128706/50570684-4051ba00-0dcf-11e9-817e-261cd28333e7.png)

![qq 20190101141322](https://user-images.githubusercontent.com/26128706/50570696-ba823e80-0dcf-11e9-898f-4324013d4a6e.png)
@Yuki-Minakami  win10,powershell那个是正常，但是cmd这个运行就是这样

**Comment by hqzh** [comment]
![_20190101181556](https://user-images.githubusercontent.com/26128706/50571961-507a9100-0df1-11e9-829c-0e8fdfebf794.png)

**Comment by Yuki-Minakami** [comment]
hi, 
关于第二个乱码问题可以参考 https://cnodejs.org/topic/502f0b07f767cc9a517baf87

不会出现乱码的代码如下

`
var spawn = require('child_process').spawn;
var ls = spawn('cmd',['dir']);

var iconv = require('iconv-lite');
ls.stdout.on('data', function(data){
    var str = iconv.decode(data,'gbk');
    console.log(str);
});

ls.stderr.on('data', function(data) {
    console.log("stderr:", data.toString());
});

ls.on('close', function(code) {
    console.log("child process exited with code",code);
});
`

**Comment by hqzh** [comment]
这是一本值得入门的书
